### ISSUE TITLE
Suggestion: Raycast AI

### ISSUE THREAD

**Issue by nyudenkov** [hakob8956/GrammariX#1]
Barev dzez! Will Raycast AI support be available instead of BYOK?

**Comment by hakob8956** [comment]
Thanks for the suggestion. Good idea. In the next version, I will include that functionality so that those who have Raycast AI don't need to provide a key.

**Comment by hakob8956** [comment]
Created [PR](https://github.com/raycast/extensions/pull/8421).
Case closed.

**Comment by nyudenkov** [comment]
Thanks!
